db:
  dsn: "root:root@tcp(localhost:3306)/zgf?charset=utf8&parseTime=true"

etcd:
  addrs:
    - "localhost:12379"

grpc:
  client:
    search:
      addr: "etcd:///service/search"

kafka:
  addr:
    - "localhost:9094"
