// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"webook/internal/controller/dynamic"
	"webook/internal/repository"
	"webook/internal/repository/cache"
	"webook/internal/repository/dao"
	"webook/internal/service"
	"webook/ioc"
)

// Injectors from wire.go:

func InitWebService() *App {
	cmdable := ioc.InitRedis()
	v := ioc.InitGinMiddleware(cmdable)
	db := ioc.InitDB()
	dynamicDao := dao.NewDynamicDao(db)
	dynamicCache := cache.NewDynamicCache(cmdable)
	dynamicRepository := repository.NewDynamicRepository(dynamicDao, dynamicCache)
	logger := ioc.InitLogger()
	dynamicService := service.NewDynamicService(dynamicRepository, logger)
	iDynamicV1 := dynamic.NewDynamicControllerV1(dynamicService, logger)
	engine := ioc.InitWebServer(v, iDynamicV1)
	app := &App{
		server: engine,
	}
	return app
}
