// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"zyz_jike/internal/repository"
	"zyz_jike/internal/repository/dao"
	"zyz_jike/internal/service"
	"zyz_jike/internal/web/article"
	"zyz_jike/internal/web/jwt"
	"zyz_jike/internal/web/user"
	"zyz_jike/ioc"
)

// Injectors from wire.go:

func InitWebServer() *App {
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisJwtHandler(cmdable)
	logger := ioc.InitLogger()
	v := ioc.InitGinMiddleware(cmdable, handler, logger)
	db := ioc.InitDB()
	userDao := dao.NewUserDao(db)
	userRepository := repository.NewUserRepository(userDao)
	userService := service.NewUserService(userRepository)
	userHandler := user.NewUserHandler(handler, userService, logger)
	articleDao := dao.NewArticleDao(db)
	articleRepository := repository.NewArticleRepository(articleDao)
	articleService := service.NewArticleService(articleRepository, userRepository, logger)
	articleHandler := article.NewArticleHandler(articleService, logger)
	engine := ioc.InitWebServer(v, userHandler, articleHandler)
	app := &App{
		Server: engine,
	}
	return app
}
